export { 
  SET_QUERY,
  SET_SEARCH_INPUT,
  SEND_REQUEST,
  SET_IS_FETCHING_MOVIES,
  SAVE_MOVIES,
  SET_NO_RESULTS,
  SET_ERROR_FETCHING_MOVIES,
  SET_CURRENT_PAGE,
  SET_TOTAL_PAGES,
  SET_IS_FETCHING_MORE_MOVIES,
  REQUEST_MORE_MOVIES,
  ADD_MORE_MOVIES,
  SET_ERROR_FETCHING_MORE_MOVIES,
  SET_SORT,
  RESET_APP, 
  setIsFetchingMovies,
  sendRequest,
  saveMovies,
  setNoResults,
  setErrorFetchingMovies,
  setQuery,
  setSearchInput,
  setCurrentPage,
  setTotalPages,
  setIsFetchingMoreMovies,
  requestMoreMovies,
  addMoreMovies,
  setErrorFetchingMoreMovies,
  setSort,
  resetApp, } from './app-actions';

